const {
    NODE_ENV, SESSION_SECRET, PORT, POSTGRESQL_DATABASE, POSTGRESQL_HOST, POSTGRESQL_PORT, POSTGRESQL_USERNAME, POSTGRESQL_PASSWORD, REDIS_URL
} = process.env;

const CONFIG = {
    SESSION_SECRET,
    POSTGRESQL_DATABASE,
    POSTGRESQL_HOST,
    POSTGRESQL_PORT,
    POSTGRESQL_USERNAME,
    POSTGRESQL_PASSWORD,
    PORT,
    REDIS_URL,
    NODE_ENV,
    limiter: {
        max: 100,
        timeWindow: '1 minute'
    }
}

export default CONFIG;